### ISSUE TITLE
Players can't see each other. Bug.

### ISSUE THREAD

**Issue by ethanccss** [skyjay1/Nomadic-Tents#14]
We love the mod and your hard work so don't take this negatively but this is the issue we're having. We have done many tests and this is all the info we have found on this issue. It's only caused by the tents and doesn't happen with the nether or anywhere else.

When leaving the tent sometimes either I or my friend can't see the other person. Usually one person can see someone but the other person can't. By entering and leaving the tent the invisible player usually becomes visible again. Though the bug is strange, sometimes the invisible person must reenter and leave the tent or the person who can't see the other player must reenter and leave again to make them visible again (sometimes multiple times 2-3). We don't quite know how it works but this is what we have figured out. Sometimes the invisible glitch happens in the tent too. I tried switching to safe mode (I was also losing XP) but that didn't help the invisible problem.

A few other points that may help find the bug:
- If I (the host ) leave first (I usually look at the door) it seems we have better luck of seeing each other, but its not always the case.
- If we leave at the same time it seems to almost always cause the invisible bug, usually I can't see my friend but they can see me when this happens.
- Sometimes when the bug happens the players model is visible but will be stuck in place with the model freaking out and shaking while the person is actually somewhere else playing normally with their true location invisible.
- Just to give you an example, if we play for an hour and use the tent 14 times, roughly half of the time we will run into the bug (or more). It's quite bad.

Very annoying as it ruins the fun of playing together. I have tried many things, changing ram didn't help. Both modern computers play minecraft no problem, no crashes. Version 1.12.2. Latest version of Nomadic tents (issue was there in the previous version too).

Feel free to ask any questions. Thanks for your help.

**Comment by skyjay1** [comment]
Hmm... I haven't heard of this bug before, but I don't usually test on a LAN server. Thanks for letting me know.

Part of the problem may relate to server-client desync when colliding with (walking into) the door block. Do you still have this problem when clicking on the door instead? If for some reason that works, you can also change the config option for "Allow Player Walk-In" so you are forced to click on the door instead of walking into it.

I'll look into the issue and see what can be done. Maybe I need to send an extra server packet after teleporting the player.
