### ISSUE TITLE
Ender Pearl in the tents

### ISSUE THREAD

**Issue by Shostraw** [skyjay1/Nomadic-Tents#15]
I used an enderpearl inside my yurt by accident and I clipped through the wall at the corner of two blocks. It tried to eject me from the yurt and then crashed the entire server I was playing on. The owner had to roll back my playerdata to put me somewhere not in limbo

**Comment by skyjay1** [comment]
Uh oh. The config file has this option:
` # When true, only creative-mode players can teleport within the Tent Dimension`
` B:"Restrict Teleporting"=true`

Have the server owner change this to "false" until I can figure out a solution. It isn't extremely important that teleporting is disabled now that I've improved the code that builds the floor of the tent - it used to leave some spots outside the tent that players could teleport to and stand on while planning a way to get into someone else's tent.

Do you have a crash log of any sort? Crash logs are pretty much the only way I can track the root cause of problems like this. Which version of Nomadic Tents are you using?

**Comment by skyjay1** [comment]
Closing as stale and unable to reproduce.
