### ISSUE TITLE
ItemColors crash and potential mod conflict

### ISSUE THREAD

**Issue by afolk2** [skyjay1/Nomadic-Tents#19]
https://pastebin.com/6NLJawsc

This crash only happens if The Midnight is installed as well. If you respond and tell me this is an issue for that mod creator I will post the issue there.

**Comment by skyjay1** [comment]
Well, that's strange. I have no idea why ItemColors registration (which I use to recolor the Shamiyana tent item) would cause a crash, and it's even stranger that it only happens when The Midnight is installed. I'll take a look when I have time (which might not be until the weekend) and try to fix it.

**Comment by Darkfiend009** [comment]
The same crash happens with Doggy Talents if  The Midnight is installed too. So i am thinking it's an issue with The Midnight.

**Comment by afolk2** [comment]
I just looked at The Midnight git and they are saying "midnight 0.4.4 is made to run on 28.0.45-28.0.51. The devs are in the process of updating the mod to run on forge versions 28.0.75 and above".
It looks like I just might have missed that, or it was never mentioned and could be causing the problem. I'll update this if it still happens after.

**Comment by skyjay1** [comment]
Ok, thank you for letting me know. I'll keep an eye on this

**Comment by skyjay1** [comment]
Probably fixed in Nomadic Tents 10.0.2, please try it out and let me know if there are still problems
