### ISSUE TITLE
The generation is messed up with Nomadic tents

### ISSUE THREAD

**Issue by matthiasrsl** [skyjay1/Nomadic-Tents#42]
Generating a world with the same seed with or without Nomadic Tents does create the same world generation. More precisely, some parts of the world will be similar, others won't.

## Reproduction
To reproduce the bug, I will give you example seed and coordinates:
Seed: 1241
At (440, 640) the world generation is the same. But if you walk 100 blocks west, a taiga biome that is present without NT is replaced by a plains biome with the mod.

Note that I have other mods installed, but this issue appears only if I add Nomadic Tents.

## More information:
**Forge Version:** 1.12.2-forge1.12.2-14.23.5.2847
**Mod Version:** 9.5.2
**Mods installed:**
AdventOfAscension 3.2.1
Backpack 3.2.0
Chest Transporter 2.8.8
Damage Indicators 
Davincis Vessels 6.340-full
GraveStone
IronChests
IvyToolkit 1.3.3
JEI 4.15.0.269
movingworld 6.342
Optifine 1.12.2_HD_U_E3
SmoothBedrock
XaerosMinimap 20.0.0

I hope I don't forget anything

**Comment by skyjay1** [comment]
This is strange, but I don't think there's anything I can do about it. I can't find anywhere in my code where I'm using the Overworld random number generator, which is the only reason I could imagine causing this problem.

**Comment by Gryffen1971** [comment]
> 
> 
> Generating a world with the same seed with or without Nomadic Tents does create the same world generation. More precisely, some parts of the world will be similar, others won't.
> ## Reproduction
> 
> To reproduce the bug, I will give you example seed and coordinates:
> Seed: 1241
> At (440, 640) the world generation is the same. But if you walk 100 blocks west, a taiga biome that is present without NT is replaced by a plains biome with the mod.
> 
> Note that I have other mods installed, but this issue appears only if I add Nomadic Tents.
> ## More information:
> 
> **Forge Version:** 1.12.2-forge1.12.2-14.23.5.2847
> **Mod Version:** 9.5.2
> **Mods installed:**
> AdventOfAscension 3.2.1
> Backpack 3.2.0
> Chest Transporter 2.8.8
> Damage Indicators
> Davincis Vessels 6.340-full
> GraveStone
> IronChests
> IvyToolkit 1.3.3
> JEI 4.15.0.269
> movingworld 6.342
> Optifine 1.12.2_HD_U_E3
> SmoothBedrock
> XaerosMinimap 20.0.0
> 
> I hope I don't forget anything



> 
> 
> This is strange, but I don't think there's anything I can do about it. I can't find anywhere in my code where I'm using the Overworld random number generator, which is the only reason I could imagine causing this problem.

I tried to reproduce the Bug using the same setup but i was unable to include Backpacks 3.2.0 because i did not know with Backpack mod was used.

I used the same seed as described above with the "Default" World Gen type. 

Test #1:  W/O Nomadic Tents, TP'd to (440.640) and found Plains Biome. Moved 100 blocks West (340,640) and still same biome. Moved 100 blocks East (540,640) still same biome. Exited game.

Test #2: With Nomadic Tents and same map. Entered game at (340,640) Still Plains Biome and at the other locations (440,640) & (540,640). 

I generated a New Map with Seed:  1241 and World Gen Type:  Large Biome.

Test #3 :  W/O Nomadic Tents, TP'd to (440.640) and found Taiga Biome.  Moved 100 blocks West (340,640) and still same biome. Moved 100 blocks East (540,640) still same biome.  Exited Game.

Test #4:  With Nomadic Tents and same map. Entered game at (340,640) Still Taiga Biome  and at the other locations (440,640) & (540,640). 

@matthiasrsl If, i could get the name (Correct Name) for the Backpack 3.2.0 Mod i will create new maps to test with said Mod.

@skyjay1 I will run more tests and let you know here when i get the correct Backpack 3.2.0 Mod installed.

**Comment by skyjay1** [comment]
1.12 is no longer supported. Sorry for any inconvenience.
