### ISSUE TITLE
Indestructable Dirt not quite so indestructable

### ISSUE THREAD

**Issue by Qsandas** [skyjay1/Nomadic-Tents#44]
Just thought I'd give you a heads-up that the indestructible dirt is vulnerable to AOE mining tools such as hammers. If you break a block next to it, the AOE will mine it as regular dirt.

**Comment by skyjay1** [comment]
Thanks for the report. It would be better to notify the owner of the mod that uses AOE tools, though, since I can't do anything from my end. 
Let them know that they should be checking that [block hardness is greater than or equal to zero](https://github.com/skyjay1/Nomadic-Tents/blob/master-1.14.4/src/main/java/nomadictents/block/BlockUnbreakable.java#L27) and/or the Block method [canEntityDestroy](https://github.com/skyjay1/Nomadic-Tents/blob/master-1.14.4/src/main/java/nomadictents/block/BlockUnbreakable.java#L54) returns true before allowing the block to be broken. If the mod author is checking some other condition that I don't provide, or if they hardcoded the AOE tool to not harvest bedrock, please let me know.
Thanks!

**Comment by skyjay1** [comment]
1.14 is no longer supported. Sorry for any inconvenience.
