### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by trestmen** [skyjay1/Nomadic-Tents#6]
Would there be anyway to add a configurable chest inside that you can turn on or off the chest and what is in the chest

**Comment by skyjay1** [comment]
You mean when the tent is first generated? Only for the Small size, or any other size? Or simply once per tent the first time it is built? What would this be used for?

**Comment by trestmen** [comment]
First time for any tent and I'm wanting to do a survival map to put basic starting items in it like minecoloes tools and what not and turn off its supply depot kinda thing 

Sent from Yahoo Mail on Android 
 
  On Sun, May 5, 2019 at 8:13 PM, Skyler James<notifications@github.com> wrote:   
You mean when the tent is first generated? Only for the Small size, or any other size? Or simply once per tent the first time it is built? What would this be used for?

**Comment by tomtenberge** [comment]
i have a similar request, i would like to have a furnace, crafting table, and portal block in every tent, i sthere any way this could be implemented? (without forking the code?)

**Comment by skyjay1** [comment]
What if I fire an event the first time a player enters a brand-new tent? Then anybody could write a small mod to handle that event and give the player certain items.

The alternative is that I design a system where blocks are specified in an external file, maybe a JSON or structure file of some sort, which would require a complete re-write of the structure generation code. It's possible but very time-consuming at my skill level.

**Comment by skyjay1** [comment]
Really, this kind of thing is outside the scope of what Nomadic Tents tries to do (provide empty space for building, not pre-built space for using). But the next release of Nomadic Tents will include some trigger events for anyone who wants to write a small mod to handle them. The modder will be able to find out if the tent is being built for the first time, if it's being upgraded, or if no changes were made to the tent since the last time somebody entered. This will allow them to place additional blocks, give the player items, even spawn mobs or whatever else they want to do.

I'd be happy to point the potential modder in the right direction if they need help with this. Really, the only event they will need to handle is `com.yurtmod.event.TentEvent.PostEnter`, which will give them access to the `World`, `TileEntityTentDoor`, and `BlockPos` of the tent. From there, the sky's the limit!

**Comment by tomtenberge** [comment]
That would be awesome! I wouldonly have to dig into how to create the mod ^¬^

**Comment by skyjay1** [comment]
Alright, the events have been added in 9.3.2. I suggest looking on Youtube for:
1. How to use and call Methods (aka Functions) in Java
2. Setting up a modding workspace for 1.12
3. Making an addon to a mod (all you do is edit the build.gradle file)
4. Event handling in 1.12

It's actually very simple once you have everything set up. The hard part is if you want the user to customize things outside the code, which requires loot tables and extra registration. Or you could find a bored modder somewhere and request an hour of their time.
If you're on Discord, there's a Minecraft Mod Development channel 
 where you can make requests or talk to modders for help

**Comment by tomtenberge** [comment]
Oh wow, thank you! I'll be sure to check it out!
